services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env.docker
    depends_on:
      - redis
    command: ["python","manage.py","runserver","0.0.0.0:8000"]

  frontend:
    build:
      context: ./ticket-frontend
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
    - REACT_APP_API_URL=http://backend:8000



  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    # command 可以在容器啟動後自動下載模型
    restart: unless-stopped

volumes:
  redis-data:
  ollama:
