# Generated by Django 4.2.16 on 2025-08-02 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="標題")),
                ("description", models.TextField(verbose_name="描述")),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("urgent", "緊急"),
                        ],
                        default="medium",
                        max_length=10,
                        verbose_name="優先級",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "開啟"),
                            ("in_progress", "處理中"),
                            ("resolved", "已解決"),
                            ("closed", "已關閉"),
                        ],
                        default="open",
                        max_length=15,
                        verbose_name="狀態",
                    ),
                ),
                ("category", models.CharField(max_length=100, verbose_name="分類")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="建立時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "ai_suggested_priority",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "低"),
                            ("medium", "中"),
                            ("high", "高"),
                            ("urgent", "緊急"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="AI建議優先級",
                    ),
                ),
                (
                    "ai_suggested_category",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="AI建議分類"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="負責人",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="建立者",
                    ),
                ),
            ],
            options={
                "verbose_name": "工單",
                "verbose_name_plural": "工單",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response_text", models.TextField(verbose_name="回覆內容")),
                (
                    "is_ai_generated",
                    models.BooleanField(default=False, verbose_name="AI生成"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="回覆時間"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="回覆者",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="tickets.ticket",
                        verbose_name="工單",
                    ),
                ),
            ],
            options={
                "verbose_name": "工單回覆",
                "verbose_name_plural": "工單回覆",
                "ordering": ["created_at"],
            },
        ),
    ]
